spring.profiles.active=local
spring.application.name=api-gateway

internal.api-key=${ROLLBACK_KEY}

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.http.server.reactive=DEBUG
logging.level.reactor.netty=INFO